@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:Set up repository;
:Check out repository and use master branch;
:Force merge to master;
:Validate Gradle wrapper;
:Setup JDK 11 for both JDK and JavaFX;
:Build and check project with Gradle;
:Run general unit tests;
:Run UI tests;
if () then ([else])
else ([if runner OS is Windows])
  :Run UI unit tests;
endif

stop

@enduml
