@startuml
!pragma useVerticalIf on
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start

: User enters add transaction command;

if () then ([else])
  :Parse exception thrown;
  stop
([All compulsory fields are present and in the correct format]) elseif () then ([else])
    :Error: Insufficient storage space for Items;
    stop
else ([Max transaction capacity is not reached])
  :Transaction successfully added ;
endif


stop

@enduml
