@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

title Budget Class Diagram


Budget "1" *-down- "1" Amount: Composition
Budget "1" *-down- "1" Interval: Composition
Interval "1" *-down- "1" BudgetInterval: Composition


@enduml