@startuml

skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start

: User enters delete_transaction command;

if () then ([else])
  :Parse exception thrown;
  stop
else ([Input is a valid number])
  :Transaction successfully deleted ;
endif


stop

@enduml
