@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "UniCash" #F4F6F6{
Class "<<interface>>\nUniCashStorage" as UniCashStorage
Class JsonUniCashStorage
Class JsonSerializableUniCash
Class JsonAdaptedTransaction
Class JsonAdaptedBudget
Class JsonAdaptedCategory
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" UniCashStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> UniCashStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonUniCashStorage .up.|> UniCashStorage
JsonUniCashStorage ..> JsonSerializableUniCash
JsonSerializableUniCash --> "*" JsonAdaptedTransaction
JsonAdaptedTransaction --> "*" JsonAdaptedCategory
JsonSerializableUniCash --> "0..1" JsonAdaptedBudget

@enduml
