
@startuml
!include ../../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":UniCashParser" as UniCashParser LOGIC_COLOR
participant ":GetTotalExpenditureCommandParser" as GetTotalExpenditureCommandParser LOGIC_COLOR
participant "command:GetTotalExpenditureCommand" as GetTotalExpenditureCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR


end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

note left LogicManager
In this sequence diagram, we set
""cmd"" = "get_total_expenditure month/7 c/Food"
""body"" = "month/7 c/Food"
end note

[-> LogicManager : execute(cmd)
activate LogicManager

LogicManager -> UniCashParser : parseCommand(cmd)
activate UniCashParser

create GetTotalExpenditureCommandParser
UniCashParser -> GetTotalExpenditureCommandParser
activate GetTotalExpenditureCommandParser

GetTotalExpenditureCommandParser --> UniCashParser
deactivate GetTotalExpenditureCommandParser

UniCashParser -> GetTotalExpenditureCommandParser : parse(body)
activate GetTotalExpenditureCommandParser

create GetTotalExpenditureCommand
GetTotalExpenditureCommandParser -> GetTotalExpenditureCommand
activate GetTotalExpenditureCommand
GetTotalExpenditureCommand --> GetTotalExpenditureCommandParser
deactivate GetTotalExpenditureCommand

GetTotalExpenditureCommandParser --> UniCashParser
deactivate GetTotalExpenditureCommandParser

UniCashParser --> LogicManager
deactivate UniCashParser
destroy GetTotalExpenditureCommandParser

LogicManager -> GetTotalExpenditureCommand : execute(model)
activate GetTotalExpenditureCommand

GetTotalExpenditureCommand -> Model : updateFilteredTransactionList(predicate)
activate Model

deactivate Model
GetTotalExpenditureCommand -> Model : getFilteredTransactionList()
activate Model

Model --> GetTotalExpenditureCommand
deactivate Model

create CommandResult
GetTotalExpenditureCommand -> CommandResult
activate CommandResult

CommandResult --> GetTotalExpenditureCommand : command result
deactivate CommandResult

GetTotalExpenditureCommand --> LogicManager : command result
deactivate GetTotalExpenditureCommand

[<--LogicManager
deactivate LogicManager
@enduml
